WIDTH = 128
HEIGHT = 64
PREVIEW_SCALE = 3
PREVIEW_SIZE = (WIDTH * PREVIEW_SCALE, HEIGHT * PREVIEW_SCALE)
PREVIEW_DISPLAY_RATIO = 0.5
PREVIEW_DISPLAY_SIZE = (
    max(1, int(round(PREVIEW_SIZE[0] * PREVIEW_DISPLAY_RATIO))),
    max(1, int(round(PREVIEW_SIZE[1] * PREVIEW_DISPLAY_RATIO))),
)
PREVIEW_BG = (196, 207, 172)
PREVIEW_FG = (34, 45, 30)
PREVIEW_BEZEL = (92, 104, 80)
PREVIEW_FRAME = (58, 67, 49)
PREVIEW_GRID = (174, 186, 150)
PREVIEW_OUTER_PAD = 20
PREVIEW_BEZEL_PAD = 10
PREVIEW_CANVAS_SIZE = (
    PREVIEW_DISPLAY_SIZE[0] + PREVIEW_OUTER_PAD * 2,
    PREVIEW_DISPLAY_SIZE[1] + PREVIEW_OUTER_PAD * 2,
)

THEME_BG = "#0f0f10"
THEME_PANEL = "#18181b"
THEME_PANEL_ALT = "#202024"
THEME_INPUT = "#111214"
THEME_FG = "#f3f3f3"
THEME_ACCENT = "#ff8c1a"
THEME_ACCENT_HOVER = "#ff9f3d"
THEME_ACCENT_DARK = "#c96a08"
THEME_BORDER = "#38383f"

DEFAULT_OUTPUT_TEXT = (
    "Load a GIF, tweak threshold / contrast with the slider or number box, then export.\n"
)